\* AUTO-GENERATED by Intent compiler — do not edit by hand.
\* Re-generate with: intent compile <source>.intent
-----------------------------------------  MODULE Nucleus_Resources_CgroupLifecycle  -----------------------------------------
EXTENDS Naturals, Sequences, TLC

\* State values (defined as strings for Apalache)
nonexistent == "nonexistent"
created == "created"
configured == "configured"
attached == "attached"
monitoring == "monitoring"
removed == "removed"

States == {
    nonexistent, created, configured, attached, monitoring, removed
}

VARIABLES
    \* @type: Str;
    state,      \* Current state
    \* @type: Int;
    pc,         \* Program counter for step tracking
    \* @type: Seq(Str);
    history,    \* Sequence of visited states (for trace analysis)
    \* @type: Seq(Str);
    event_queue     \* Pending events/messages queue

vars == <<state, pc, history, event_queue>>

Init ==
    /\ state = nonexistent
    /\ pc = 0
    /\ history = <<>>
    /\ event_queue = <<>>

\* Transition actions
nonexistent_create_cgroup ==
    /\ state = nonexistent
    /\ state' = created
    /\ pc' = pc + 1
    /\ history' = Append(history, state)
    /\ event_queue' = event_queue

created_set_limits ==
    /\ state = created
    /\ state' = configured
    /\ pc' = pc + 1
    /\ history' = Append(history, state)
    /\ event_queue' = event_queue

configured_attach_process ==
    /\ state = configured
    /\ state' = attached
    /\ pc' = pc + 1
    /\ history' = Append(history, state)
    /\ event_queue' = event_queue

attached_start_monitoring ==
    /\ state = attached
    /\ state' = monitoring
    /\ pc' = pc + 1
    /\ history' = Append(history, state)
    /\ event_queue' = event_queue

monitoring_cleanup ==
    /\ state = monitoring
    /\ state' = removed
    /\ pc' = pc + 1
    /\ history' = Append(history, state)
    /\ event_queue' = event_queue

created_cleanup_failed_cgroup ==
    /\ state = created
    /\ state' = removed
    /\ pc' = pc + 1
    /\ history' = Append(history, state)
    /\ event_queue' = event_queue

configured_cleanup_failed_cgroup ==
    /\ state = configured
    /\ state' = removed
    /\ pc' = pc + 1
    /\ history' = Append(history, state)
    /\ event_queue' = event_queue

Next ==
    \/ nonexistent_create_cgroup
    \/ created_set_limits
    \/ configured_attach_process
    \/ attached_start_monitoring
    \/ monitoring_cleanup
    \/ created_cleanup_failed_cgroup
    \/ configured_cleanup_failed_cgroup
    \/ UNCHANGED vars

\* Stuttering step (system does nothing)
Stutter ==
    UNCHANGED vars

Spec ==
    /\ Init
    /\ [][Next]_vars

\* Type invariant
TypeOK ==
    /\ state \in States
    /\ pc \in Nat
    \* history: checked via HistoryConsistent (Seq(States) unsupported by Apalache)

\* Terminal states
TerminalStates == {removed}

\* Once in terminal state, cannot leave
TerminalStable ==
    [](state \in TerminalStates => [](state \in TerminalStates))

\* History length matches step count
HistoryConsistent ==
    Len(history) = pc

\* Temporal properties (LTL)
Prop_resource_limits_enforced == [][(state = configured) => (((state' = attached) \/ (state' = monitoring)) \/ (state' = removed))]_vars
Prop_cleanup_guaranteed == []((state = created) => (<>(state = removed)))
Prop_no_resource_leak == [][(state = removed) => (state' = removed)]_vars

\* Liveness: Eventually reaches a terminal state
Liveness ==
    <>(state \in {removed})

\* Deadlock freedom: From every non-terminal state, some action is enabled
DeadlockFree ==
    [](state \notin TerminalStates => ENABLED(Next))

\* Reachability helpers for model checking
CanReach_nonexistent == <>(state = nonexistent)
CanReach_created == <>(state = created)
CanReach_configured == <>(state = configured)
CanReach_attached == <>(state = attached)
CanReach_monitoring == <>(state = monitoring)
CanReach_removed == <>(state = removed)

=====================================================
