\* AUTO-GENERATED by Intent compiler — do not edit by hand.
\* Re-generate with: intent compile <source>.intent
---------------------------------------------------------------------  MODULE NucleusVerification_FormalVerification_NamespaceIsolationSpec  ---------------------------------------------------------------------
EXTENDS Naturals, Sequences, TLC

\* State values (defined as strings for Apalache)
unverified == "unverified"
verified == "verified"

States == {
    unverified, verified
}

VARIABLES
    \* @type: Str;
    state,      \* Current state
    \* @type: Int;
    pc,         \* Program counter for step tracking
    \* @type: Seq(Str);
    history,    \* Sequence of visited states (for trace analysis)
    \* @type: Seq(Str);
    event_queue     \* Pending events/messages queue

vars == <<state, pc, history, event_queue>>

Init ==
    /\ state = unverified
    /\ pc = 0
    /\ history = <<>>
    /\ event_queue = <<>>

\* Transition actions
unverified_apalache_check ==
    /\ state = unverified
    /\ state' = verified
    /\ pc' = pc + 1
    /\ history' = Append(history, state)
    /\ event_queue' = event_queue

Next ==
    \/ unverified_apalache_check
    \/ UNCHANGED vars

\* Stuttering step (system does nothing)
Stutter ==
    UNCHANGED vars

Spec ==
    /\ Init
    /\ [][Next]_vars

\* Type invariant
TypeOK ==
    /\ state \in States
    /\ pc \in Nat
    \* history: checked via HistoryConsistent (Seq(States) unsupported by Apalache)

\* Terminal states
TerminalStates == {verified}

\* Once in terminal state, cannot leave
TerminalStable ==
    [](state \in TerminalStates => [](state \in TerminalStates))

\* History length matches step count
HistoryConsistent ==
    Len(history) = pc

\* Temporal properties (LTL)
Prop_model_verified == []((state = unverified) => (<>(state = verified)))

\* Liveness: Eventually reaches a terminal state
Liveness ==
    <>(state \in {verified})

\* Deadlock freedom: From every non-terminal state, some action is enabled
DeadlockFree ==
    [](state \notin TerminalStates => ENABLED(Next))

\* Reachability helpers for model checking
CanReach_unverified == <>(state = unverified)
CanReach_verified == <>(state = verified)

=================================================================================
