\* AUTO-GENERATED by Intent compiler – do not edit by hand.
\* Re-generate with: intent compile <source>.intent
--------------------------------------------  MODULE Nucleus_Security_SecurityEnforcement  --------------------------------------------
EXTENDS Naturals, Sequences, TLC

\* State values (defined as strings for Apalache)
privileged == "privileged"
capabilities_dropped == "capabilities_dropped"
seccomp_applied == "seccomp_applied"
landlock_applied == "landlock_applied"
locked == "locked"

States == {
    privileged, capabilities_dropped, seccomp_applied, landlock_applied, locked
}

VARIABLES
    \* @type: Str;
    state,      \* Current state
    \* @type: Int;
    pc,         \* Program counter for step tracking
    \* @type: Seq(Str);
    history,    \* Sequence of visited states (for trace analysis)
    \* @type: Seq(Str);
    event_queue,     \* Pending events/messages queue
    \* @type: Str;
    action_taken,     \* MBT: name of the last action (for tla-connect replay)
    \* @type: Bool;
    capabilities_are_dropped,
    \* @type: Bool;
    seccomp_filter_active,
    \* @type: Bool;
    landlock_policy_active

vars == <<state, pc, history, event_queue, action_taken, capabilities_are_dropped, seccomp_filter_active, landlock_policy_active>>

Init ==
    /\ state = privileged
    /\ pc = 0
    /\ history = <<>>
    /\ event_queue = <<>>
    /\ action_taken = "init"
    /\ capabilities_are_dropped = FALSE
    /\ seccomp_filter_active = FALSE
    /\ landlock_policy_active = FALSE

\* Transition actions
privileged_drop_capabilities ==
    /\ state = privileged
    /\ state' = capabilities_dropped
    /\ pc' = pc + 1
    /\ history' = Append(history, state)
    /\ event_queue' = event_queue
    /\ action_taken' = "privileged_drop_capabilities"
    /\ capabilities_are_dropped' = TRUE
    /\ seccomp_filter_active' = seccomp_filter_active
    /\ landlock_policy_active' = landlock_policy_active

capabilities_dropped_apply_seccomp ==
    /\ state = capabilities_dropped
    /\ state' = seccomp_applied
    /\ pc' = pc + 1
    /\ history' = Append(history, state)
    /\ event_queue' = event_queue
    /\ action_taken' = "capabilities_dropped_apply_seccomp"
    /\ capabilities_are_dropped' = capabilities_are_dropped
    /\ seccomp_filter_active' = TRUE
    /\ landlock_policy_active' = landlock_policy_active

seccomp_applied_apply_landlock ==
    /\ state = seccomp_applied
    /\ state' = landlock_applied
    /\ pc' = pc + 1
    /\ history' = Append(history, state)
    /\ event_queue' = event_queue
    /\ action_taken' = "seccomp_applied_apply_landlock"
    /\ capabilities_are_dropped' = capabilities_are_dropped
    /\ seccomp_filter_active' = seccomp_filter_active
    /\ landlock_policy_active' = TRUE

landlock_applied_finalize ==
    /\ state = landlock_applied
    /\ state' = locked
    /\ pc' = pc + 1
    /\ history' = Append(history, state)
    /\ event_queue' = event_queue
    /\ action_taken' = "landlock_applied_finalize"
    /\ capabilities_are_dropped' = capabilities_are_dropped
    /\ seccomp_filter_active' = seccomp_filter_active
    /\ landlock_policy_active' = landlock_policy_active

Next ==
    \/ privileged_drop_capabilities
    \/ capabilities_dropped_apply_seccomp
    \/ seccomp_applied_apply_landlock
    \/ landlock_applied_finalize
    \/ UNCHANGED vars

\* Stuttering step (system does nothing)
Stutter ==
    UNCHANGED vars

Spec ==
    /\ Init
    /\ [][Next]_vars

\* Type invariant
TypeOK ==
    /\ state \in States
    /\ pc \in Nat
    /\ capabilities_are_dropped \in BOOLEAN
    /\ seccomp_filter_active \in BOOLEAN
    /\ landlock_policy_active \in BOOLEAN
    \* history: checked via HistoryConsistent (Seq(States) unsupported by Apalache)

\* Terminal states
TerminalStates == {locked}

\* Once in terminal state, cannot leave
TerminalStable ==
    [](state \in TerminalStates => [](state \in TerminalStates))

\* History length matches step count
HistoryConsistent ==
    Len(history) = pc

\* Temporal properties (LTL)
Prop_irreversible_lockdown == [][(state = seccomp_applied) => ((state' = seccomp_applied) \/ (state' = landlock_applied))]_vars
Prop_landlock_lockdown == [][(state = landlock_applied) => ((state' = landlock_applied) \/ (state' = locked))]_vars
Prop_defense_in_depth == [](state = locked => capabilities_are_dropped /\ seccomp_filter_active /\ landlock_policy_active)
Prop_no_privilege_escalation == [][(state = capabilities_dropped) => (~(state' = privileged))]_vars

\* State invariant for trace generation (negated to find terminating traces)
NotTerminated == state \notin TerminalStates

\* Liveness: Eventually reaches a terminal state
Liveness ==
    <>(state \in {locked})

\* Deadlock freedom: From every non-terminal state, some action is enabled
DeadlockFree ==
    [](state \notin TerminalStates => ENABLED(Next))

\* Reachability helpers for model checking
CanReach_privileged == <>(state = privileged)
CanReach_capabilities_dropped == <>(state = capabilities_dropped)
CanReach_seccomp_applied == <>(state = seccomp_applied)
CanReach_landlock_applied == <>(state = landlock_applied)
CanReach_locked == <>(state = locked)

========================================================
