\* AUTO-GENERATED by Intent compiler — do not edit by hand.
\* Re-generate with: intent compile <source>.intent
---------------------------------------------------------------------  MODULE NucleusVerification_FormalVerification_NamespaceIsolationSpec  ---------------------------------------------------------------------
EXTENDS Naturals, Sequences, TLC

\* State constants
CONSTANTS
    unverified, verified

States == {
    unverified, verified
}

VARIABLES
    state,      \* Current state
    pc,         \* Program counter for step tracking
    history,    \* Sequence of visited states (for trace analysis)
    pending     \* Pending events/messages queue

vars == <<state, pc, history, pending>>

Init ==
    /\ state = unverified
    /\ pc = 0
    /\ history = <<>>
    /\ pending = <<>>

\* Transition actions
unverified_apalache_check ==
    /\ state = unverified
    /\ state' = verified
    /\ pc' = pc + 1
    /\ history' = Append(history, state)
    /\ pending' = pending

Next ==
    \/ unverified_apalache_check

\* Stuttering step (system does nothing)
Stutter ==
    UNCHANGED vars

Spec ==
    /\ Init
    /\ [][Next]_vars

\* Type invariant
TypeOK ==
    /\ state \in States
    /\ pc \in Nat
    /\ history \in Seq(States)

\* Terminal states
TerminalStates == {verified}

\* Once in terminal state, cannot leave
TerminalStable ==
    [](state \in TerminalStates => [](state \in TerminalStates))

\* History length matches step count
HistoryConsistent ==
    Len(history) = pc

\* Temporal properties (LTL)
Prop_model_verified == []((state = unverified) => (<>(state = verified)))

\* Liveness: Eventually reaches a terminal state
Liveness ==
    <>(state \in {verified})

\* Deadlock freedom: From every non-terminal state, some action is enabled
DeadlockFree ==
    [](state \notin TerminalStates => ENABLED(Next))

\* Reachability helpers for model checking
CanReach_unverified == <>(state = unverified)
CanReach_verified == <>(state = verified)

=================================================================================
