\* AUTO-GENERATED by Intent compiler – do not edit by hand.
\* Re-generate with: intent compile <source>.intent
-----------------------------------------------------  MODULE NucleusSecurity_Namespaces_NamespaceIsolation  -----------------------------------------------------
EXTENDS Naturals, Sequences, TLC

\* State values (defined as strings for Apalache)
host_view == "host_view"
isolated_view == "isolated_view"

States == {
    host_view, isolated_view
}

VARIABLES
    \* @type: Str;
    state,      \* Current state
    \* @type: Int;
    pc,         \* Program counter for step tracking
    \* @type: Seq(Str);
    history,    \* Sequence of visited states (for trace analysis)
    \* @type: Seq(Str);
    event_queue,     \* Pending events/messages queue
    \* @type: Bool;
    can_see_host_pids,
    \* @type: Bool;
    can_access_host_fs,
    \* @type: Bool;
    has_network_access,
    \* @type: Bool;
    can_access_host_ipc,
    \* @type: Bool;
    user_namespace_remapped

vars == <<state, pc, history, event_queue, can_see_host_pids, can_access_host_fs, has_network_access, can_access_host_ipc, user_namespace_remapped>>

Init ==
    /\ state = host_view
    /\ pc = 0
    /\ history = <<>>
    /\ event_queue = <<>>
    /\ can_see_host_pids = TRUE
    /\ can_access_host_fs = TRUE
    /\ has_network_access = TRUE
    /\ can_access_host_ipc = TRUE
    /\ user_namespace_remapped = FALSE

\* Transition actions
host_view_enter_namespace ==
    /\ state = host_view
    /\ state' = isolated_view
    /\ pc' = pc + 1
    /\ history' = Append(history, state)
    /\ event_queue' = event_queue
    /\ can_see_host_pids' = FALSE
    /\ can_access_host_fs' = FALSE
    /\ has_network_access' = FALSE
    /\ can_access_host_ipc' = FALSE
    /\ user_namespace_remapped' = TRUE

Next ==
    \/ host_view_enter_namespace
    \/ UNCHANGED vars

\* Stuttering step (system does nothing)
Stutter ==
    UNCHANGED vars

Spec ==
    /\ Init
    /\ [][Next]_vars

\* Type invariant
TypeOK ==
    /\ state \in States
    /\ pc \in Nat
    /\ can_see_host_pids \in BOOLEAN
    /\ can_access_host_fs \in BOOLEAN
    /\ has_network_access \in BOOLEAN
    /\ can_access_host_ipc \in BOOLEAN
    /\ user_namespace_remapped \in BOOLEAN
    \* history: checked via HistoryConsistent (Seq(States) unsupported by Apalache)

\* Terminal states
TerminalStates == {isolated_view}

\* Once in terminal state, cannot leave
TerminalStable ==
    [](state \in TerminalStates => [](state \in TerminalStates))

\* History length matches step count
HistoryConsistent ==
    Len(history) = pc

\* Temporal properties (LTL)
Prop_pid_isolation == [](state = isolated_view => ~can_see_host_pids)
Prop_mount_isolation == [](state = isolated_view => ~can_access_host_fs)
Prop_network_isolation == [](state = isolated_view => ~has_network_access)
Prop_ipc_isolation == [](state = isolated_view => ~can_access_host_ipc)
Prop_user_namespace_remapped == [](state = isolated_view => user_namespace_remapped)
Prop_isolation_complete == []((state = host_view) => (<>(state = isolated_view)))

IsolationSafety ==
    /\ Prop_pid_isolation
    /\ Prop_mount_isolation
    /\ Prop_network_isolation
    /\ Prop_ipc_isolation
    /\ Prop_user_namespace_remapped

\* Liveness: Eventually reaches a terminal state
Liveness ==
    <>(state \in {isolated_view})

\* Deadlock freedom: From every non-terminal state, some action is enabled
DeadlockFree ==
    [](state \notin TerminalStates => ENABLED(Next))

\* Reachability helpers for model checking
CanReach_host_view == <>(state = host_view)
CanReach_isolated_view == <>(state = isolated_view)

=================================================================
