\* AUTO-GENERATED by Intent compiler — do not edit by hand.
\* Re-generate with: intent compile <source>.intent
--------------------------------------------  MODULE NucleusSecurity_GVisor_GVisorRuntime  --------------------------------------------
EXTENDS Naturals, Sequences, TLC

\* State constants
CONSTANTS
    native_kernel, gvisor_kernel

States == {
    native_kernel, gvisor_kernel
}

VARIABLES
    state,      \* Current state
    pc,         \* Program counter for step tracking
    history,    \* Sequence of visited states (for trace analysis)
    pending     \* Pending events/messages queue

vars == <<state, pc, history, pending>>

Init ==
    /\ state = native_kernel
    /\ pc = 0
    /\ history = <<>>
    /\ pending = <<>>

\* Transition actions
native_kernel_enable_gvisor ==
    /\ state = native_kernel
    /\ state' = gvisor_kernel
    /\ pc' = pc + 1
    /\ history' = Append(history, state)
    /\ pending' = pending

Next ==
    \/ native_kernel_enable_gvisor

\* Stuttering step (system does nothing)
Stutter ==
    UNCHANGED vars

Spec ==
    /\ Init
    /\ [][Next]_vars

\* Type invariant
TypeOK ==
    /\ state \in States
    /\ pc \in Nat
    /\ history \in Seq(States)

\* Terminal states
TerminalStates == {gvisor_kernel}

\* Once in terminal state, cannot leave
TerminalStable ==
    [](state \in TerminalStates => [](state \in TerminalStates))

\* History length matches step count
HistoryConsistent ==
    Len(history) = pc

\* Temporal properties (LTL)
Prop_kernel_switched == []((state = native_kernel) => (<>(state = gvisor_kernel)))

\* Liveness: Eventually reaches a terminal state
Liveness ==
    <>(state \in {gvisor_kernel})

\* Deadlock freedom: From every non-terminal state, some action is enabled
DeadlockFree ==
    [](state \notin TerminalStates => ENABLED(Next))

\* Reachability helpers for model checking
CanReach_native_kernel == <>(state = native_kernel)
CanReach_gvisor_kernel == <>(state = gvisor_kernel)

========================================================
