\* AUTO-GENERATED by Intent compiler – do not edit by hand.
\* Re-generate with: intent compile <source>.intent
--------------------------------------------  MODULE NucleusSecurity_GVisor_GVisorRuntime  --------------------------------------------
EXTENDS Naturals, Sequences, TLC

\* State values (defined as strings for Apalache)
native_kernel == "native_kernel"
gvisor_kernel == "gvisor_kernel"

States == {
    native_kernel, gvisor_kernel
}

VARIABLES
    \* @type: Str;
    state,      \* Current state
    \* @type: Int;
    pc,         \* Program counter for step tracking
    \* @type: Seq(Str);
    history,    \* Sequence of visited states (for trace analysis)
    \* @type: Seq(Str);
    event_queue,     \* Pending events/messages queue
    \* @type: Bool;
    all_syscalls_intercepted,
    \* @type: Int;
    kernel_syscalls

vars == <<state, pc, history, event_queue, all_syscalls_intercepted, kernel_syscalls>>

Init ==
    /\ state = native_kernel
    /\ pc = 0
    /\ history = <<>>
    /\ event_queue = <<>>
    /\ all_syscalls_intercepted = FALSE
    /\ kernel_syscalls = 300

\* Transition actions
native_kernel_enable_gvisor ==
    /\ state = native_kernel
    /\ state' = gvisor_kernel
    /\ pc' = pc + 1
    /\ history' = Append(history, state)
    /\ event_queue' = event_queue
    /\ all_syscalls_intercepted' = TRUE
    /\ kernel_syscalls' = 99

Next ==
    \/ native_kernel_enable_gvisor
    \/ UNCHANGED vars

\* Stuttering step (system does nothing)
Stutter ==
    UNCHANGED vars

Spec ==
    /\ Init
    /\ [][Next]_vars

\* Type invariant
TypeOK ==
    /\ state \in States
    /\ pc \in Nat
    /\ all_syscalls_intercepted \in BOOLEAN
    /\ kernel_syscalls \in Nat
    \* history: checked via HistoryConsistent (Seq(States) unsupported by Apalache)

\* Terminal states
TerminalStates == {gvisor_kernel}

\* Once in terminal state, cannot leave
TerminalStable ==
    [](state \in TerminalStates => [](state \in TerminalStates))

\* History length matches step count
HistoryConsistent ==
    Len(history) = pc

\* Temporal properties (LTL)
Prop_kernel_switched == []((state = native_kernel) => (<>(state = gvisor_kernel)))
Prop_syscall_interception == [](state = gvisor_kernel => all_syscalls_intercepted)
Prop_reduced_surface == [](state = gvisor_kernel => kernel_syscalls < 100)

GVisorSafety ==
    /\ Prop_syscall_interception
    /\ Prop_reduced_surface

\* Liveness: Eventually reaches a terminal state
Liveness ==
    <>(state \in {gvisor_kernel})

\* Deadlock freedom: From every non-terminal state, some action is enabled
DeadlockFree ==
    [](state \notin TerminalStates => ENABLED(Next))

\* Reachability helpers for model checking
CanReach_native_kernel == <>(state = native_kernel)
CanReach_gvisor_kernel == <>(state = gvisor_kernel)

========================================================
