\* AUTO-GENERATED by Intent compiler – do not edit by hand.
\* Re-generate with: intent compile <source>.intent
--------------------------------------------------  MODULE NucleusSecurity_Seccomp_SeccompEnforcement  --------------------------------------------------
EXTENDS Naturals, Sequences, TLC

\* State values (defined as strings for Apalache)
no_filter == "no_filter"
whitelist_active == "whitelist_active"

States == {
    no_filter, whitelist_active
}

DangerousSyscalls == {
    "ptrace",
    "kexec_load",
    "bpf",
    "userfaultfd",
    "perf_event_open",
    "io_uring_setup"
}

EssentialSyscalls == {
    "read",
    "write",
    "open",
    "close",
    "exit",
    "exit_group"
}

Syscalls == DangerousSyscalls \cup EssentialSyscalls

VARIABLES
    \* @type: Str;
    state,      \* Current state
    \* @type: Int;
    pc,         \* Program counter for step tracking
    \* @type: Seq(Str);
    history,    \* Sequence of visited states (for trace analysis)
    \* @type: Seq(Str);
    event_queue,     \* Pending events/messages queue
    \* @type: Set(Str);
    allowed_syscalls,
    \* @type: Bool;
    default_allow,
    \* @type: Bool;
    seccomp_fail_closed,
    \* @type: Bool;
    no_new_privileges

vars == <<state, pc, history, event_queue, allowed_syscalls, default_allow, seccomp_fail_closed, no_new_privileges>>

Init ==
    /\ state = no_filter
    /\ pc = 0
    /\ history = <<>>
    /\ event_queue = <<>>
    /\ allowed_syscalls = Syscalls
    /\ default_allow = TRUE
    /\ seccomp_fail_closed = FALSE
    /\ no_new_privileges = FALSE

\* Transition actions
no_filter_apply_seccomp_filter ==
    /\ state = no_filter
    /\ state' = whitelist_active
    /\ pc' = pc + 1
    /\ history' = Append(history, state)
    /\ event_queue' = event_queue
    /\ allowed_syscalls' = EssentialSyscalls
    /\ default_allow' = FALSE
    /\ seccomp_fail_closed' = TRUE
    /\ no_new_privileges' = TRUE

Next ==
    \/ no_filter_apply_seccomp_filter
    \/ UNCHANGED vars

\* Stuttering step (system does nothing)
Stutter ==
    UNCHANGED vars

Spec ==
    /\ Init
    /\ [][Next]_vars

\* Type invariant
TypeOK ==
    /\ state \in States
    /\ pc \in Nat
    /\ allowed_syscalls \in SUBSET Syscalls
    /\ default_allow \in BOOLEAN
    /\ seccomp_fail_closed \in BOOLEAN
    /\ no_new_privileges \in BOOLEAN
    \* history: checked via HistoryConsistent (Seq(States) unsupported by Apalache)

\* Terminal states
TerminalStates == {whitelist_active}

\* Once in terminal state, cannot leave
TerminalStable ==
    [](state \in TerminalStates => [](state \in TerminalStates))

\* History length matches step count
HistoryConsistent ==
    Len(history) = pc

\* Temporal properties (LTL)
Prop_irreversible == [][(state = whitelist_active) => (state' = whitelist_active)]_vars
Prop_no_dangerous_syscalls == [](state = whitelist_active => DangerousSyscalls \cap allowed_syscalls = {})
Prop_whitelist_default_deny == [](state = whitelist_active => ~default_allow)
Prop_fail_closed == [](state = whitelist_active => seccomp_fail_closed)
Prop_no_new_privileges == [](state = whitelist_active => no_new_privileges)

SeccompSafety ==
    /\ Prop_irreversible
    /\ Prop_no_dangerous_syscalls
    /\ Prop_whitelist_default_deny
    /\ Prop_fail_closed
    /\ Prop_no_new_privileges

\* Liveness: Eventually reaches a terminal state
Liveness ==
    <>(state \in {whitelist_active})

\* Deadlock freedom: From every non-terminal state, some action is enabled
DeadlockFree ==
    [](state \notin TerminalStates => ENABLED(Next))

\* Reachability helpers for model checking
CanReach_no_filter == <>(state = no_filter)
CanReach_whitelist_active == <>(state = whitelist_active)

==============================================================
