\* AUTO-GENERATED by Intent compiler — do not edit by hand.
\* Re-generate with: intent compile <source>.intent
----------------------------------------------  MODULE Nucleus_Filesystem_FilesystemLifecycle  ----------------------------------------------
EXTENDS Naturals, Sequences, TLC

\* State constants
CONSTANTS
    unmounted, mounted, populated, pivoted, unmounted_final

States == {
    unmounted, mounted, populated, pivoted, unmounted_final
}

VARIABLES
    state,      \* Current state
    pc,         \* Program counter for step tracking
    history,    \* Sequence of visited states (for trace analysis)
    pending     \* Pending events/messages queue

vars == <<state, pc, history, pending>>

Init ==
    /\ state = unmounted
    /\ pc = 0
    /\ history = <<>>
    /\ pending = <<>>

\* Transition actions
unmounted_mount_tmpfs ==
    /\ state = unmounted
    /\ state' = mounted
    /\ pc' = pc + 1
    /\ history' = Append(history, state)
    /\ pending' = pending

mounted_populate_context ==
    /\ state = mounted
    /\ state' = populated
    /\ pc' = pc + 1
    /\ history' = Append(history, state)
    /\ pending' = pending

populated_pivot_root ==
    /\ state = populated
    /\ state' = pivoted
    /\ pc' = pc + 1
    /\ history' = Append(history, state)
    /\ pending' = pending

pivoted_cleanup ==
    /\ state = pivoted
    /\ state' = unmounted_final
    /\ pc' = pc + 1
    /\ history' = Append(history, state)
    /\ pending' = pending

Next ==
    \/ unmounted_mount_tmpfs
    \/ mounted_populate_context
    \/ populated_pivot_root
    \/ pivoted_cleanup

\* Stuttering step (system does nothing)
Stutter ==
    UNCHANGED vars

Spec ==
    /\ Init
    /\ [][Next]_vars

\* Type invariant
TypeOK ==
    /\ state \in States
    /\ pc \in Nat
    /\ history \in Seq(States)

\* Terminal states
TerminalStates == {unmounted_final}

\* Once in terminal state, cannot leave
TerminalStable ==
    [](state \in TerminalStates => [](state \in TerminalStates))

\* History length matches step count
HistoryConsistent ==
    Len(history) = pc

\* Temporal properties (LTL)
Prop_context_isolation == []((state = pivoted) => (((state = pivoted) \/ (state = unmounted_final))'))
Prop_ephemeral_guarantee == []((state = unmounted_final) => ((state = unmounted_final)'))
Prop_mount_ordering == []((state = populated) => (((state = pivoted) \/ (state = unmounted_final))'))

\* Liveness: Eventually reaches a terminal state
Liveness ==
    <>(state \in {unmounted_final})

\* Deadlock freedom: From every non-terminal state, some action is enabled
DeadlockFree ==
    [](state \notin TerminalStates => ENABLED(Next))

\* Reachability helpers for model checking
CanReach_unmounted == <>(state = unmounted)
CanReach_mounted == <>(state = mounted)
CanReach_populated == <>(state = populated)
CanReach_pivoted == <>(state = pivoted)
CanReach_unmounted_final == <>(state = unmounted_final)

==========================================================
