\* AUTO-GENERATED by Intent compiler – do not edit by hand.
\* Re-generate with: intent compile <source>.intent
-------------------------------------------------------------------  MODULE NucleusVerification_IntegrationTests_ContainerLifecycleTest  -------------------------------------------------------------------
EXTENDS Naturals, Sequences, TLC

\* State values (defined as strings for Apalache)
test_start == "test_start"
container_created == "container_created"
container_running == "container_running"
container_exited == "container_exited"
cleanup_done == "cleanup_done"

States == {
    test_start, container_created, container_running, container_exited, cleanup_done
}

VARIABLES
    \* @type: Str;
    state,      \* Current state
    \* @type: Int;
    pc,         \* Program counter for step tracking
    \* @type: Seq(Str);
    history,    \* Sequence of visited states (for trace analysis)
    \* @type: Seq(Str);
    event_queue     \* Pending events/messages queue

vars == <<state, pc, history, event_queue>>

Init ==
    /\ state = test_start
    /\ pc = 0
    /\ history = <<>>
    /\ event_queue = <<>>

\* Transition actions
test_start_create_container ==
    /\ state = test_start
    /\ state' = container_created
    /\ pc' = pc + 1
    /\ history' = Append(history, state)
    /\ event_queue' = event_queue

container_created_start_container ==
    /\ state = container_created
    /\ state' = container_running
    /\ pc' = pc + 1
    /\ history' = Append(history, state)
    /\ event_queue' = event_queue

container_running_wait_exit ==
    /\ state = container_running
    /\ state' = container_exited
    /\ pc' = pc + 1
    /\ history' = Append(history, state)
    /\ event_queue' = event_queue

container_exited_verify_cleanup ==
    /\ state = container_exited
    /\ state' = cleanup_done
    /\ pc' = pc + 1
    /\ history' = Append(history, state)
    /\ event_queue' = event_queue

Next ==
    \/ test_start_create_container
    \/ container_created_start_container
    \/ container_running_wait_exit
    \/ container_exited_verify_cleanup
    \/ UNCHANGED vars

\* Stuttering step (system does nothing)
Stutter ==
    UNCHANGED vars

Spec ==
    /\ Init
    /\ [][Next]_vars

\* Type invariant
TypeOK ==
    /\ state \in States
    /\ pc \in Nat
    \* history: checked via HistoryConsistent (Seq(States) unsupported by Apalache)

\* Terminal states
TerminalStates == {cleanup_done}

\* Once in terminal state, cannot leave
TerminalStable ==
    [](state \in TerminalStates => [](state \in TerminalStates))

\* History length matches step count
HistoryConsistent ==
    Len(history) = pc

\* Temporal properties (LTL)
Prop_eventual_cleanup == []((state = test_start) => (<>(state = cleanup_done)))

\* Liveness: Eventually reaches a terminal state
Liveness ==
    <>(state \in {cleanup_done})

\* Deadlock freedom: From every non-terminal state, some action is enabled
DeadlockFree ==
    [](state \notin TerminalStates => ENABLED(Next))

\* Reachability helpers for model checking
CanReach_test_start == <>(state = test_start)
CanReach_container_created == <>(state = container_created)
CanReach_container_running == <>(state = container_running)
CanReach_container_exited == <>(state = container_exited)
CanReach_cleanup_done == <>(state = cleanup_done)

===============================================================================
