\* AUTO-GENERATED by Intent compiler — do not edit by hand.
\* Re-generate with: intent compile <source>.intent
--------------------------------------------  MODULE Nucleus_Isolation_NamespaceLifecycle  --------------------------------------------
EXTENDS Naturals, Sequences, TLC

\* State constants
CONSTANTS
    uninitialized, unshared, entered, cleaned

States == {
    uninitialized, unshared, entered, cleaned
}

VARIABLES
    state,      \* Current state
    pc,         \* Program counter for step tracking
    history,    \* Sequence of visited states (for trace analysis)
    pending     \* Pending events/messages queue

vars == <<state, pc, history, pending>>

Init ==
    /\ state = uninitialized
    /\ pc = 0
    /\ history = <<>>
    /\ pending = <<>>

\* Transition actions
uninitialized_create_namespaces ==
    /\ state = uninitialized
    /\ state' = unshared
    /\ pc' = pc + 1
    /\ history' = Append(history, state)
    /\ pending' = pending

unshared_enter_namespaces ==
    /\ state = unshared
    /\ state' = entered
    /\ pc' = pc + 1
    /\ history' = Append(history, state)
    /\ pending' = pending

entered_cleanup ==
    /\ state = entered
    /\ state' = cleaned
    /\ pc' = pc + 1
    /\ history' = Append(history, state)
    /\ pending' = pending

Next ==
    \/ uninitialized_create_namespaces
    \/ unshared_enter_namespaces
    \/ entered_cleanup

\* Stuttering step (system does nothing)
Stutter ==
    UNCHANGED vars

Spec ==
    /\ Init
    /\ [][Next]_vars

\* Type invariant
TypeOK ==
    /\ state \in States
    /\ pc \in Nat
    /\ history \in Seq(States)

\* Terminal states
TerminalStates == {cleaned}

\* Once in terminal state, cannot leave
TerminalStable ==
    [](state \in TerminalStates => [](state \in TerminalStates))

\* History length matches step count
HistoryConsistent ==
    Len(history) = pc

\* Temporal properties (LTL)
Prop_isolation_integrity == []((state = entered) => (((state = entered) \/ (state = cleaned))'))
Prop_cleanup_happens == []((state = entered) => (<>(state = cleaned)))

\* Liveness: Eventually reaches a terminal state
Liveness ==
    <>(state \in {cleaned})

\* Deadlock freedom: From every non-terminal state, some action is enabled
DeadlockFree ==
    [](state \notin TerminalStates => ENABLED(Next))

\* Reachability helpers for model checking
CanReach_uninitialized == <>(state = uninitialized)
CanReach_unshared == <>(state = unshared)
CanReach_entered == <>(state = entered)
CanReach_cleaned == <>(state = cleaned)

========================================================
