\* AUTO-GENERATED by Intent compiler — do not edit by hand.
\* Re-generate with: intent compile <source>.intent
--------------------------------------------  MODULE Nucleus_Security_SecurityEnforcement  --------------------------------------------
EXTENDS Naturals, Sequences, TLC

\* State values (defined as strings for Apalache)
privileged == "privileged"
capabilities_dropped == "capabilities_dropped"
seccomp_applied == "seccomp_applied"
locked == "locked"

States == {
    privileged, capabilities_dropped, seccomp_applied, locked
}

VARIABLES
    \* @type: Str;
    state,      \* Current state
    \* @type: Int;
    pc,         \* Program counter for step tracking
    \* @type: Seq(Str);
    history,    \* Sequence of visited states (for trace analysis)
    \* @type: Seq(Str);
    event_queue     \* Pending events/messages queue

vars == <<state, pc, history, event_queue>>

Init ==
    /\ state = privileged
    /\ pc = 0
    /\ history = <<>>
    /\ event_queue = <<>>

\* Transition actions
privileged_drop_capabilities ==
    /\ state = privileged
    /\ state' = capabilities_dropped
    /\ pc' = pc + 1
    /\ history' = Append(history, state)
    /\ event_queue' = event_queue

capabilities_dropped_apply_seccomp ==
    /\ state = capabilities_dropped
    /\ state' = seccomp_applied
    /\ pc' = pc + 1
    /\ history' = Append(history, state)
    /\ event_queue' = event_queue

seccomp_applied_finalize ==
    /\ state = seccomp_applied
    /\ state' = locked
    /\ pc' = pc + 1
    /\ history' = Append(history, state)
    /\ event_queue' = event_queue

Next ==
    \/ privileged_drop_capabilities
    \/ capabilities_dropped_apply_seccomp
    \/ seccomp_applied_finalize
    \/ UNCHANGED vars

\* Stuttering step (system does nothing)
Stutter ==
    UNCHANGED vars

Spec ==
    /\ Init
    /\ [][Next]_vars

\* Type invariant
TypeOK ==
    /\ state \in States
    /\ pc \in Nat
    \* history: checked via HistoryConsistent (Seq(States) unsupported by Apalache)

\* Terminal states
TerminalStates == {locked}

\* Once in terminal state, cannot leave
TerminalStable ==
    [](state \in TerminalStates => [](state \in TerminalStates))

\* History length matches step count
HistoryConsistent ==
    Len(history) = pc

\* Temporal properties (LTL)
Prop_irreversible_lockdown == [][(state = seccomp_applied) => ((state' = seccomp_applied) \/ (state' = locked))]_vars
Prop_defense_in_depth == []((state = locked) => ((state = capabilities_dropped) /\ (state = seccomp_applied)))
Prop_no_privilege_escalation == [][(state = capabilities_dropped) => (~(state' = privileged))]_vars

\* Liveness: Eventually reaches a terminal state
Liveness ==
    <>(state \in {locked})

\* Deadlock freedom: From every non-terminal state, some action is enabled
DeadlockFree ==
    [](state \notin TerminalStates => ENABLED(Next))

\* Reachability helpers for model checking
CanReach_privileged == <>(state = privileged)
CanReach_capabilities_dropped == <>(state = capabilities_dropped)
CanReach_seccomp_applied == <>(state = seccomp_applied)
CanReach_locked == <>(state = locked)

========================================================
