\* AUTO-GENERATED by Intent compiler — do not edit by hand.
\* Re-generate with: intent compile <source>.intent
-----------------------------------------  MODULE Nucleus_Resources_CgroupLifecycle  -----------------------------------------
EXTENDS Naturals, Sequences, TLC

\* State constants
CONSTANTS
    nonexistent, created, configured, attached, monitoring, removed

States == {
    nonexistent, created, configured, attached, monitoring, removed
}

VARIABLES
    state,      \* Current state
    pc,         \* Program counter for step tracking
    history,    \* Sequence of visited states (for trace analysis)
    pending     \* Pending events/messages queue

vars == <<state, pc, history, pending>>

Init ==
    /\ state = nonexistent
    /\ pc = 0
    /\ history = <<>>
    /\ pending = <<>>

\* Transition actions
nonexistent_create_cgroup ==
    /\ state = nonexistent
    /\ state' = created
    /\ pc' = pc + 1
    /\ history' = Append(history, state)
    /\ pending' = pending

created_set_limits ==
    /\ state = created
    /\ state' = configured
    /\ pc' = pc + 1
    /\ history' = Append(history, state)
    /\ pending' = pending

configured_attach_process ==
    /\ state = configured
    /\ state' = attached
    /\ pc' = pc + 1
    /\ history' = Append(history, state)
    /\ pending' = pending

attached_start_monitoring ==
    /\ state = attached
    /\ state' = monitoring
    /\ pc' = pc + 1
    /\ history' = Append(history, state)
    /\ pending' = pending

monitoring_cleanup ==
    /\ state = monitoring
    /\ state' = removed
    /\ pc' = pc + 1
    /\ history' = Append(history, state)
    /\ pending' = pending

created_cleanup_failed_cgroup ==
    /\ state = created
    /\ state' = removed
    /\ pc' = pc + 1
    /\ history' = Append(history, state)
    /\ pending' = pending

configured_cleanup_failed_cgroup ==
    /\ state = configured
    /\ state' = removed
    /\ pc' = pc + 1
    /\ history' = Append(history, state)
    /\ pending' = pending

Next ==
    \/ nonexistent_create_cgroup
    \/ created_set_limits
    \/ configured_attach_process
    \/ attached_start_monitoring
    \/ monitoring_cleanup
    \/ created_cleanup_failed_cgroup
    \/ configured_cleanup_failed_cgroup

\* Stuttering step (system does nothing)
Stutter ==
    UNCHANGED vars

Spec ==
    /\ Init
    /\ [][Next]_vars

\* Type invariant
TypeOK ==
    /\ state \in States
    /\ pc \in Nat
    /\ history \in Seq(States)

\* Terminal states
TerminalStates == {removed}

\* Once in terminal state, cannot leave
TerminalStable ==
    [](state \in TerminalStates => [](state \in TerminalStates))

\* History length matches step count
HistoryConsistent ==
    Len(history) = pc

\* Temporal properties (LTL)
Prop_resource_limits_enforced == []((state = configured) => ((((state = attached) \/ (state = monitoring)) \/ (state = removed))'))
Prop_cleanup_guaranteed == []((state = created) => (<>(state = removed)))
Prop_no_resource_leak == []((state = removed) => ((state = removed)'))

\* Liveness: Eventually reaches a terminal state
Liveness ==
    <>(state \in {removed})

\* Deadlock freedom: From every non-terminal state, some action is enabled
DeadlockFree ==
    [](state \notin TerminalStates => ENABLED(Next))

\* Reachability helpers for model checking
CanReach_nonexistent == <>(state = nonexistent)
CanReach_created == <>(state = created)
CanReach_configured == <>(state = configured)
CanReach_attached == <>(state = attached)
CanReach_monitoring == <>(state = monitoring)
CanReach_removed == <>(state = removed)

=====================================================
