\* AUTO-GENERATED by Intent compiler — do not edit by hand.
\* Re-generate with: intent compile <source>.intent
-------------------------------------------------------  MODULE NucleusSecurity_Capabilities_CapabilityDropping  -------------------------------------------------------
EXTENDS Naturals, Sequences, TLC

\* State constants
CONSTANTS
    all_caps, minimal_caps, no_caps

States == {
    all_caps, minimal_caps, no_caps
}

VARIABLES
    state,      \* Current state
    pc,         \* Program counter for step tracking
    history,    \* Sequence of visited states (for trace analysis)
    pending     \* Pending events/messages queue

vars == <<state, pc, history, pending>>

Init ==
    /\ state = all_caps
    /\ pc = 0
    /\ history = <<>>
    /\ pending = <<>>

\* Transition actions
all_caps_drop_most_capabilities ==
    /\ state = all_caps
    /\ state' = minimal_caps
    /\ pc' = pc + 1
    /\ history' = Append(history, state)
    /\ pending' = pending

all_caps_drop_all_capabilities ==
    /\ state = all_caps
    /\ state' = no_caps
    /\ pc' = pc + 1
    /\ history' = Append(history, state)
    /\ pending' = pending

minimal_caps_drop_remaining_capabilities ==
    /\ state = minimal_caps
    /\ state' = no_caps
    /\ pc' = pc + 1
    /\ history' = Append(history, state)
    /\ pending' = pending

Next ==
    \/ all_caps_drop_most_capabilities
    \/ all_caps_drop_all_capabilities
    \/ minimal_caps_drop_remaining_capabilities

\* Stuttering step (system does nothing)
Stutter ==
    UNCHANGED vars

Spec ==
    /\ Init
    /\ [][Next]_vars

\* Type invariant
TypeOK ==
    /\ state \in States
    /\ pc \in Nat
    /\ history \in Seq(States)

\* Terminal states
TerminalStates == {no_caps}

\* Once in terminal state, cannot leave
TerminalStable ==
    [](state \in TerminalStates => [](state \in TerminalStates))

\* History length matches step count
HistoryConsistent ==
    Len(history) = pc

\* Temporal properties (LTL)
Prop_irreversible == []((state = minimal_caps) => (((state = minimal_caps) \/ (state = no_caps))'))

\* Liveness: Eventually reaches a terminal state
Liveness ==
    <>(state \in {no_caps})

\* Deadlock freedom: From every non-terminal state, some action is enabled
DeadlockFree ==
    [](state \notin TerminalStates => ENABLED(Next))

\* Reachability helpers for model checking
CanReach_all_caps == <>(state = all_caps)
CanReach_minimal_caps == <>(state = minimal_caps)
CanReach_no_caps == <>(state = no_caps)

===================================================================
