\* AUTO-GENERATED by Intent compiler – do not edit by hand.
\* Re-generate with: intent compile <source>.intent
-----------------------------------------  MODULE Nucleus_Resources_CgroupLifecycle  -----------------------------------------
EXTENDS Naturals, Sequences, TLC

\* State values (defined as strings for Apalache)
nonexistent == "nonexistent"
created == "created"
configured == "configured"
attached == "attached"
monitoring == "monitoring"
removed == "removed"

States == {
    nonexistent, created, configured, attached, monitoring, removed
}

VARIABLES
    \* @type: Str;
    state,      \* Current state
    \* @type: Int;
    pc,         \* Program counter for step tracking
    \* @type: Seq(Str);
    history,    \* Sequence of visited states (for trace analysis)
    \* @type: Seq(Str);
    event_queue,     \* Pending events/messages queue
    \* @type: Str;
    action_taken,     \* MBT: name of the last action (for tla-connect replay)
    \* @type: Int;
    processes_in_cgroup

vars == <<state, pc, history, event_queue, action_taken, processes_in_cgroup>>

Init ==
    /\ state = nonexistent
    /\ pc = 0
    /\ history = <<>>
    /\ event_queue = <<>>
    /\ action_taken = "init"
    /\ processes_in_cgroup = 0

\* Transition actions
nonexistent_create_cgroup ==
    /\ state = nonexistent
    /\ state' = created
    /\ pc' = pc + 1
    /\ history' = Append(history, state)
    /\ event_queue' = event_queue
    /\ action_taken' = "nonexistent_create_cgroup"
    /\ processes_in_cgroup' = 0

created_set_limits ==
    /\ state = created
    /\ state' = configured
    /\ pc' = pc + 1
    /\ history' = Append(history, state)
    /\ event_queue' = event_queue
    /\ action_taken' = "created_set_limits"
    /\ processes_in_cgroup' = 0

configured_attach_process ==
    /\ state = configured
    /\ state' = attached
    /\ pc' = pc + 1
    /\ history' = Append(history, state)
    /\ event_queue' = event_queue
    /\ action_taken' = "configured_attach_process"
    /\ processes_in_cgroup' = 1

attached_start_monitoring ==
    /\ state = attached
    /\ state' = monitoring
    /\ pc' = pc + 1
    /\ history' = Append(history, state)
    /\ event_queue' = event_queue
    /\ action_taken' = "attached_start_monitoring"
    /\ processes_in_cgroup' = processes_in_cgroup

monitoring_cleanup ==
    /\ state = monitoring
    /\ state' = removed
    /\ pc' = pc + 1
    /\ history' = Append(history, state)
    /\ event_queue' = event_queue
    /\ action_taken' = "monitoring_cleanup"
    /\ processes_in_cgroup' = 0

created_cleanup_failed_cgroup ==
    /\ state = created
    /\ state' = removed
    /\ pc' = pc + 1
    /\ history' = Append(history, state)
    /\ event_queue' = event_queue
    /\ action_taken' = "created_cleanup_failed_cgroup"
    /\ processes_in_cgroup' = 0

configured_cleanup_failed_cgroup ==
    /\ state = configured
    /\ state' = removed
    /\ pc' = pc + 1
    /\ history' = Append(history, state)
    /\ event_queue' = event_queue
    /\ action_taken' = "configured_cleanup_failed_cgroup"
    /\ processes_in_cgroup' = 0

attached_cleanup ==
    /\ state = attached
    /\ state' = removed
    /\ pc' = pc + 1
    /\ history' = Append(history, state)
    /\ event_queue' = event_queue
    /\ action_taken' = "attached_cleanup"
    /\ processes_in_cgroup' = 0

Next ==
    \/ nonexistent_create_cgroup
    \/ created_set_limits
    \/ configured_attach_process
    \/ attached_start_monitoring
    \/ monitoring_cleanup
    \/ created_cleanup_failed_cgroup
    \/ configured_cleanup_failed_cgroup
    \/ attached_cleanup
    \/ UNCHANGED vars

\* Stuttering step (system does nothing)
Stutter ==
    UNCHANGED vars

Spec ==
    /\ Init
    /\ [][Next]_vars

\* Type invariant
TypeOK ==
    /\ state \in States
    /\ pc \in Nat
    /\ processes_in_cgroup \in Nat
    \* history: checked via HistoryConsistent (Seq(States) unsupported by Apalache)

\* Terminal states
TerminalStates == {removed}

\* Once in terminal state, cannot leave
TerminalStable ==
    [](state \in TerminalStates => [](state \in TerminalStates))

\* History length matches step count
HistoryConsistent ==
    Len(history) = pc

\* Temporal properties (LTL)
Prop_resource_limits_enforced == [][(state = configured) => (((state' = attached) \/ (state' = monitoring)) \/ (state' = removed))]_vars
Prop_cleanup_guaranteed == []((state = created) => (<>(state = removed)))
Prop_no_resource_leak == [](state = removed => processes_in_cgroup = 0)

\* State invariant for trace generation (negated to find terminating traces)
NotTerminated == state \notin TerminalStates

\* Liveness: Eventually reaches a terminal state
Liveness ==
    <>(state \in {removed})

\* Deadlock freedom: From every non-terminal state, some action is enabled
DeadlockFree ==
    [](state \notin TerminalStates => ENABLED(Next))

\* Reachability helpers for model checking
CanReach_nonexistent == <>(state = nonexistent)
CanReach_created == <>(state = created)
CanReach_configured == <>(state = configured)
CanReach_attached == <>(state = attached)
CanReach_monitoring == <>(state = monitoring)
CanReach_removed == <>(state = removed)

=====================================================
