\* AUTO-GENERATED by Intent compiler — do not edit by hand.
\* Re-generate with: intent compile <source>.intent
-----------------------------------------------------  MODULE NucleusSecurity_Namespaces_NamespaceIsolation  -----------------------------------------------------
EXTENDS Naturals, Sequences, TLC

\* State constants
CONSTANTS
    host_view, isolated_view

States == {
    host_view, isolated_view
}

VARIABLES
    state,      \* Current state
    pc,         \* Program counter for step tracking
    history,    \* Sequence of visited states (for trace analysis)
    pending     \* Pending events/messages queue

vars == <<state, pc, history, pending>>

Init ==
    /\ state = host_view
    /\ pc = 0
    /\ history = <<>>
    /\ pending = <<>>

\* Transition actions
host_view_enter_namespace ==
    /\ state = host_view
    /\ state' = isolated_view
    /\ pc' = pc + 1
    /\ history' = Append(history, state)
    /\ pending' = pending

Next ==
    \/ host_view_enter_namespace

\* Stuttering step (system does nothing)
Stutter ==
    UNCHANGED vars

Spec ==
    /\ Init
    /\ [][Next]_vars

\* Type invariant
TypeOK ==
    /\ state \in States
    /\ pc \in Nat
    /\ history \in Seq(States)

\* Terminal states
TerminalStates == {isolated_view}

\* Once in terminal state, cannot leave
TerminalStable ==
    [](state \in TerminalStates => [](state \in TerminalStates))

\* History length matches step count
HistoryConsistent ==
    Len(history) = pc

\* Temporal properties (LTL)
Prop_isolation_complete == []((state = host_view) => (<>(state = isolated_view)))

\* Liveness: Eventually reaches a terminal state
Liveness ==
    <>(state \in {isolated_view})

\* Deadlock freedom: From every non-terminal state, some action is enabled
DeadlockFree ==
    [](state \notin TerminalStates => ENABLED(Next))

\* Reachability helpers for model checking
CanReach_host_view == <>(state = host_view)
CanReach_isolated_view == <>(state = isolated_view)

=================================================================
