\* AUTO-GENERATED by Intent compiler — do not edit by hand.
\* Re-generate with: intent compile <source>.intent
--------------------------------------------  MODULE Nucleus_Security_SecurityEnforcement  --------------------------------------------
EXTENDS Naturals, Sequences, TLC

\* State constants
CONSTANTS
    privileged, capabilities_dropped, seccomp_applied, locked

States == {
    privileged, capabilities_dropped, seccomp_applied, locked
}

VARIABLES
    state,      \* Current state
    pc,         \* Program counter for step tracking
    history,    \* Sequence of visited states (for trace analysis)
    pending     \* Pending events/messages queue

vars == <<state, pc, history, pending>>

Init ==
    /\ state = privileged
    /\ pc = 0
    /\ history = <<>>
    /\ pending = <<>>

\* Transition actions
privileged_drop_capabilities ==
    /\ state = privileged
    /\ state' = capabilities_dropped
    /\ pc' = pc + 1
    /\ history' = Append(history, state)
    /\ pending' = pending

capabilities_dropped_apply_seccomp ==
    /\ state = capabilities_dropped
    /\ state' = seccomp_applied
    /\ pc' = pc + 1
    /\ history' = Append(history, state)
    /\ pending' = pending

seccomp_applied_finalize ==
    /\ state = seccomp_applied
    /\ state' = locked
    /\ pc' = pc + 1
    /\ history' = Append(history, state)
    /\ pending' = pending

Next ==
    \/ privileged_drop_capabilities
    \/ capabilities_dropped_apply_seccomp
    \/ seccomp_applied_finalize

\* Stuttering step (system does nothing)
Stutter ==
    UNCHANGED vars

Spec ==
    /\ Init
    /\ [][Next]_vars

\* Type invariant
TypeOK ==
    /\ state \in States
    /\ pc \in Nat
    /\ history \in Seq(States)

\* Terminal states
TerminalStates == {locked}

\* Once in terminal state, cannot leave
TerminalStable ==
    [](state \in TerminalStates => [](state \in TerminalStates))

\* History length matches step count
HistoryConsistent ==
    Len(history) = pc

\* Temporal properties (LTL)
Prop_irreversible_lockdown == []((state = seccomp_applied) => (((state = seccomp_applied) \/ (state = locked))'))
Prop_defense_in_depth == []((state = locked) => ((state = capabilities_dropped) /\ (state = seccomp_applied)))
Prop_no_privilege_escalation == []((state = capabilities_dropped) => ((~(state = privileged))'))

\* Liveness: Eventually reaches a terminal state
Liveness ==
    <>(state \in {locked})

\* Deadlock freedom: From every non-terminal state, some action is enabled
DeadlockFree ==
    [](state \notin TerminalStates => ENABLED(Next))

\* Reachability helpers for model checking
CanReach_privileged == <>(state = privileged)
CanReach_capabilities_dropped == <>(state = capabilities_dropped)
CanReach_seccomp_applied == <>(state = seccomp_applied)
CanReach_locked == <>(state = locked)

========================================================
