\* AUTO-GENERATED by Intent compiler – do not edit by hand.
\* Re-generate with: intent compile <source>.intent
------------------------------------------------  MODULE NucleusSecurity_Cgroups_ResourceLimiting  ------------------------------------------------
EXTENDS Naturals, Sequences, TLC

\* State values (defined as strings for Apalache)
unlimited == "unlimited"
limited == "limited"

States == {
    unlimited, limited
}

VARIABLES
    \* @type: Str;
    state,      \* Current state
    \* @type: Int;
    pc,         \* Program counter for step tracking
    \* @type: Seq(Str);
    history,    \* Sequence of visited states (for trace analysis)
    \* @type: Seq(Str);
    event_queue     \* Pending events/messages queue

vars == <<state, pc, history, event_queue>>

Init ==
    /\ state = unlimited
    /\ pc = 0
    /\ history = <<>>
    /\ event_queue = <<>>

\* Transition actions
unlimited_set_cgroup_limits ==
    /\ state = unlimited
    /\ state' = limited
    /\ pc' = pc + 1
    /\ history' = Append(history, state)
    /\ event_queue' = event_queue

Next ==
    \/ unlimited_set_cgroup_limits
    \/ UNCHANGED vars

\* Stuttering step (system does nothing)
Stutter ==
    UNCHANGED vars

Spec ==
    /\ Init
    /\ [][Next]_vars

\* Type invariant
TypeOK ==
    /\ state \in States
    /\ pc \in Nat
    \* history: checked via HistoryConsistent (Seq(States) unsupported by Apalache)

\* Terminal states
TerminalStates == {limited}

\* Once in terminal state, cannot leave
TerminalStable ==
    [](state \in TerminalStates => [](state \in TerminalStates))

\* History length matches step count
HistoryConsistent ==
    Len(history) = pc

\* Temporal properties (LTL)
Prop_limits_enforced == []((state = unlimited) => (<>(state = limited)))

\* Liveness: Eventually reaches a terminal state
Liveness ==
    <>(state \in {limited})

\* Deadlock freedom: From every non-terminal state, some action is enabled
DeadlockFree ==
    [](state \notin TerminalStates => ENABLED(Next))

\* Reachability helpers for model checking
CanReach_unlimited == <>(state = unlimited)
CanReach_limited == <>(state = limited)

============================================================
