\* AUTO-GENERATED by Intent compiler – do not edit by hand.
\* Re-generate with: intent compile <source>.intent
----------------------------------------------------------------  MODULE NucleusVerification_FormalVerification_ResourceLimitSpec  ----------------------------------------------------------------
EXTENDS Naturals, Sequences, TLC

\* State values (defined as strings for Apalache)
unverified == "unverified"
verified == "verified"

States == {
    unverified, verified
}

VARIABLES
    \* @type: Str;
    state,      \* Current state
    \* @type: Int;
    pc,         \* Program counter for step tracking
    \* @type: Seq(Str);
    history,    \* Sequence of visited states (for trace analysis)
    \* @type: Seq(Str);
    event_queue,     \* Pending events/messages queue
    \* @type: Bool;
    memory_limit_checked,
    \* @type: Bool;
    pids_limit_checked,
    \* @type: Bool;
    cpu_limit_checked,
    \* @type: Bool;
    cleanup_checked,
    \* @type: Bool;
    apalache_passed

vars == <<state, pc, history, event_queue, memory_limit_checked, pids_limit_checked, cpu_limit_checked, cleanup_checked, apalache_passed>>

Init ==
    /\ state = unverified
    /\ pc = 0
    /\ history = <<>>
    /\ event_queue = <<>>
    /\ memory_limit_checked = FALSE
    /\ pids_limit_checked = FALSE
    /\ cpu_limit_checked = FALSE
    /\ cleanup_checked = FALSE
    /\ apalache_passed = FALSE

\* Transition actions
unverified_apalache_check ==
    /\ state = unverified
    /\ state' = verified
    /\ pc' = pc + 1
    /\ history' = Append(history, state)
    /\ event_queue' = event_queue
    /\ memory_limit_checked' = TRUE
    /\ pids_limit_checked' = TRUE
    /\ cpu_limit_checked' = TRUE
    /\ cleanup_checked' = TRUE
    /\ apalache_passed' = TRUE

Next ==
    \/ unverified_apalache_check
    \/ UNCHANGED vars

\* Stuttering step (system does nothing)
Stutter ==
    UNCHANGED vars

Spec ==
    /\ Init
    /\ [][Next]_vars

\* Type invariant
TypeOK ==
    /\ state \in States
    /\ pc \in Nat
    /\ memory_limit_checked \in BOOLEAN
    /\ pids_limit_checked \in BOOLEAN
    /\ cpu_limit_checked \in BOOLEAN
    /\ cleanup_checked \in BOOLEAN
    /\ apalache_passed \in BOOLEAN
    \* history: checked via HistoryConsistent (Seq(States) unsupported by Apalache)

\* Terminal states
TerminalStates == {verified}

\* Once in terminal state, cannot leave
TerminalStable ==
    [](state \in TerminalStates => [](state \in TerminalStates))

\* History length matches step count
HistoryConsistent ==
    Len(history) = pc

\* Temporal properties (LTL)
Prop_model_verified == []((state = unverified) => (<>(state = verified)))
Prop_verified_covers_resource_limits == [](state = verified => apalache_passed /\ memory_limit_checked /\ pids_limit_checked /\ cpu_limit_checked /\ cleanup_checked)

\* Liveness: Eventually reaches a terminal state
Liveness ==
    <>(state \in {verified})

\* Deadlock freedom: From every non-terminal state, some action is enabled
DeadlockFree ==
    [](state \notin TerminalStates => ENABLED(Next))

\* Reachability helpers for model checking
CanReach_unverified == <>(state = unverified)
CanReach_verified == <>(state = verified)

============================================================================
