\* AUTO-GENERATED by Intent compiler — do not edit by hand.
\* Re-generate with: intent compile <source>.intent
--------------------------------------------  MODULE Nucleus_Isolation_NamespaceLifecycle  --------------------------------------------
EXTENDS Naturals, Sequences, TLC

\* State values (defined as strings for Apalache)
uninitialized == "uninitialized"
unshared == "unshared"
entered == "entered"
cleaned == "cleaned"

States == {
    uninitialized, unshared, entered, cleaned
}

VARIABLES
    \* @type: Str;
    state,      \* Current state
    \* @type: Int;
    pc,         \* Program counter for step tracking
    \* @type: Seq(Str);
    history,    \* Sequence of visited states (for trace analysis)
    \* @type: Seq(Str);
    event_queue,     \* Pending events/messages queue
    \* @type: Str;
    action_taken     \* MBT: name of the last action (for tla-connect replay)

vars == <<state, pc, history, event_queue, action_taken>>

Init ==
    /\ state = uninitialized
    /\ pc = 0
    /\ history = <<>>
    /\ event_queue = <<>>
    /\ action_taken = "init"

\* Transition actions
uninitialized_create_namespaces ==
    /\ state = uninitialized
    /\ state' = unshared
    /\ pc' = pc + 1
    /\ history' = Append(history, state)
    /\ event_queue' = event_queue
    /\ action_taken' = "uninitialized_create_namespaces"

unshared_enter_namespaces ==
    /\ state = unshared
    /\ state' = entered
    /\ pc' = pc + 1
    /\ history' = Append(history, state)
    /\ event_queue' = event_queue
    /\ action_taken' = "unshared_enter_namespaces"

entered_cleanup ==
    /\ state = entered
    /\ state' = cleaned
    /\ pc' = pc + 1
    /\ history' = Append(history, state)
    /\ event_queue' = event_queue
    /\ action_taken' = "entered_cleanup"

Next ==
    \/ uninitialized_create_namespaces
    \/ unshared_enter_namespaces
    \/ entered_cleanup
    \/ UNCHANGED vars

\* Stuttering step (system does nothing)
Stutter ==
    UNCHANGED vars

Spec ==
    /\ Init
    /\ [][Next]_vars

\* Type invariant
TypeOK ==
    /\ state \in States
    /\ pc \in Nat
    \* history: checked via HistoryConsistent (Seq(States) unsupported by Apalache)

\* Terminal states
TerminalStates == {cleaned}

\* Once in terminal state, cannot leave
TerminalStable ==
    [](state \in TerminalStates => [](state \in TerminalStates))

\* History length matches step count
HistoryConsistent ==
    Len(history) = pc

\* Temporal properties (LTL)
Prop_isolation_integrity == [][(state = entered) => ((state' = entered) \/ (state' = cleaned))]_vars
Prop_cleanup_happens == []((state = entered) => (<>(state = cleaned)))

\* State invariant for trace generation (negated to find terminating traces)
NotTerminated == state \notin TerminalStates

\* Liveness: Eventually reaches a terminal state
Liveness ==
    <>(state \in {cleaned})

\* Deadlock freedom: From every non-terminal state, some action is enabled
DeadlockFree ==
    [](state \notin TerminalStates => ENABLED(Next))

\* Reachability helpers for model checking
CanReach_uninitialized == <>(state = uninitialized)
CanReach_unshared == <>(state = unshared)
CanReach_entered == <>(state = entered)
CanReach_cleaned == <>(state = cleaned)

========================================================
