\* AUTO-GENERATED by Intent compiler – do not edit by hand.
\* Re-generate with: intent compile <source>.intent
-------------------------------------------------------  MODULE NucleusSecurity_Capabilities_CapabilityDropping  -------------------------------------------------------
EXTENDS Naturals, Sequences, TLC

\* State values (defined as strings for Apalache)
all_caps == "all_caps"
minimal_caps == "minimal_caps"
no_caps == "no_caps"

States == {
    all_caps, minimal_caps, no_caps
}

VARIABLES
    \* @type: Str;
    state,      \* Current state
    \* @type: Int;
    pc,         \* Program counter for step tracking
    \* @type: Seq(Str);
    history,    \* Sequence of visited states (for trace analysis)
    \* @type: Seq(Str);
    event_queue     \* Pending events/messages queue

vars == <<state, pc, history, event_queue>>

Init ==
    /\ state = all_caps
    /\ pc = 0
    /\ history = <<>>
    /\ event_queue = <<>>

\* Transition actions
all_caps_drop_most_capabilities ==
    /\ state = all_caps
    /\ state' = minimal_caps
    /\ pc' = pc + 1
    /\ history' = Append(history, state)
    /\ event_queue' = event_queue

all_caps_drop_all_capabilities ==
    /\ state = all_caps
    /\ state' = no_caps
    /\ pc' = pc + 1
    /\ history' = Append(history, state)
    /\ event_queue' = event_queue

minimal_caps_drop_remaining_capabilities ==
    /\ state = minimal_caps
    /\ state' = no_caps
    /\ pc' = pc + 1
    /\ history' = Append(history, state)
    /\ event_queue' = event_queue

Next ==
    \/ all_caps_drop_most_capabilities
    \/ all_caps_drop_all_capabilities
    \/ minimal_caps_drop_remaining_capabilities
    \/ UNCHANGED vars

\* Stuttering step (system does nothing)
Stutter ==
    UNCHANGED vars

Spec ==
    /\ Init
    /\ [][Next]_vars

\* Type invariant
TypeOK ==
    /\ state \in States
    /\ pc \in Nat
    \* history: checked via HistoryConsistent (Seq(States) unsupported by Apalache)

\* Terminal states
TerminalStates == {no_caps}

\* Once in terminal state, cannot leave
TerminalStable ==
    [](state \in TerminalStates => [](state \in TerminalStates))

\* History length matches step count
HistoryConsistent ==
    Len(history) = pc

\* Temporal properties (LTL)
Prop_irreversible == [][(state = minimal_caps) => ((state' = minimal_caps) \/ (state' = no_caps))]_vars

\* Liveness: Eventually reaches a terminal state
Liveness ==
    <>(state \in {no_caps})

\* Deadlock freedom: From every non-terminal state, some action is enabled
DeadlockFree ==
    [](state \notin TerminalStates => ENABLED(Next))

\* Reachability helpers for model checking
CanReach_all_caps == <>(state = all_caps)
CanReach_minimal_caps == <>(state = minimal_caps)
CanReach_no_caps == <>(state = no_caps)

===================================================================
