\* AUTO-GENERATED by Intent compiler – do not edit by hand.
\* Re-generate with: intent compile <source>.intent
----------------------------------------------------  MODULE NucleusSecurity_ResourceExhaustionPrevention  ----------------------------------------------------
EXTENDS Naturals, Sequences, TLC

\* State values (defined as strings for Apalache)
normal_usage == "normal_usage"
throttled == "throttled"
oom_killed == "oom_killed"

States == {
    normal_usage, throttled, oom_killed
}

VARIABLES
    \* @type: Str;
    state,      \* Current state
    \* @type: Int;
    pc,         \* Program counter for step tracking
    \* @type: Seq(Str);
    history,    \* Sequence of visited states (for trace analysis)
    \* @type: Seq(Str);
    event_queue     \* Pending events/messages queue

vars == <<state, pc, history, event_queue>>

Init ==
    /\ state = normal_usage
    /\ pc = 0
    /\ history = <<>>
    /\ event_queue = <<>>

\* Transition actions
normal_usage_exceed_soft_limit ==
    /\ state = normal_usage
    /\ state' = throttled
    /\ pc' = pc + 1
    /\ history' = Append(history, state)
    /\ event_queue' = event_queue

throttled_reduce_usage ==
    /\ state = throttled
    /\ state' = normal_usage
    /\ pc' = pc + 1
    /\ history' = Append(history, state)
    /\ event_queue' = event_queue

throttled_exceed_hard_limit ==
    /\ state = throttled
    /\ state' = oom_killed
    /\ pc' = pc + 1
    /\ history' = Append(history, state)
    /\ event_queue' = event_queue

Next ==
    \/ normal_usage_exceed_soft_limit
    \/ throttled_reduce_usage
    \/ throttled_exceed_hard_limit
    \/ UNCHANGED vars

\* Stuttering step (system does nothing)
Stutter ==
    UNCHANGED vars

Spec ==
    /\ Init
    /\ [][Next]_vars

\* Type invariant
TypeOK ==
    /\ state \in States
    /\ pc \in Nat
    \* history: checked via HistoryConsistent (Seq(States) unsupported by Apalache)

\* Terminal states
TerminalStates == {oom_killed}

\* Once in terminal state, cannot leave
TerminalStable ==
    [](state \in TerminalStates => [](state \in TerminalStates))

\* History length matches step count
HistoryConsistent ==
    Len(history) = pc

\* Temporal properties (LTL)
Prop_eventual_termination == []((state = throttled) => (<>((state = oom_killed) \/ (state = normal_usage))))

\* Liveness: Eventually reaches a terminal state
Liveness ==
    <>(state \in {oom_killed})

\* Deadlock freedom: From every non-terminal state, some action is enabled
DeadlockFree ==
    [](state \notin TerminalStates => ENABLED(Next))

\* Reachability helpers for model checking
CanReach_normal_usage == <>(state = normal_usage)
CanReach_throttled == <>(state = throttled)
CanReach_oom_killed == <>(state = oom_killed)

================================================================
