\* AUTO-GENERATED by Intent compiler — do not edit by hand.
\* Re-generate with: intent compile <source>.intent
--------------------------------------------------  MODULE NucleusSecurity_Seccomp_SeccompEnforcement  --------------------------------------------------
EXTENDS Naturals, Sequences, TLC

\* State values (defined as strings for Apalache)
no_filter == "no_filter"
whitelist_active == "whitelist_active"

States == {
    no_filter, whitelist_active
}

VARIABLES
    \* @type: Str;
    state,      \* Current state
    \* @type: Int;
    pc,         \* Program counter for step tracking
    \* @type: Seq(Str);
    history,    \* Sequence of visited states (for trace analysis)
    \* @type: Seq(Str);
    event_queue     \* Pending events/messages queue

vars == <<state, pc, history, event_queue>>

Init ==
    /\ state = no_filter
    /\ pc = 0
    /\ history = <<>>
    /\ event_queue = <<>>

\* Transition actions
no_filter_apply_seccomp_filter ==
    /\ state = no_filter
    /\ state' = whitelist_active
    /\ pc' = pc + 1
    /\ history' = Append(history, state)
    /\ event_queue' = event_queue

Next ==
    \/ no_filter_apply_seccomp_filter
    \/ UNCHANGED vars

\* Stuttering step (system does nothing)
Stutter ==
    UNCHANGED vars

Spec ==
    /\ Init
    /\ [][Next]_vars

\* Type invariant
TypeOK ==
    /\ state \in States
    /\ pc \in Nat
    \* history: checked via HistoryConsistent (Seq(States) unsupported by Apalache)

\* Terminal states
TerminalStates == {whitelist_active}

\* Once in terminal state, cannot leave
TerminalStable ==
    [](state \in TerminalStates => [](state \in TerminalStates))

\* History length matches step count
HistoryConsistent ==
    Len(history) = pc

\* Temporal properties (LTL)
Prop_irreversible == [][(state = whitelist_active) => (state' = whitelist_active)]_vars

\* Liveness: Eventually reaches a terminal state
Liveness ==
    <>(state \in {whitelist_active})

\* Deadlock freedom: From every non-terminal state, some action is enabled
DeadlockFree ==
    [](state \notin TerminalStates => ENABLED(Next))

\* Reachability helpers for model checking
CanReach_no_filter == <>(state = no_filter)
CanReach_whitelist_active == <>(state = whitelist_active)

==============================================================
