\* AUTO-GENERATED by Intent compiler — do not edit by hand.
\* Re-generate with: intent compile <source>.intent
-------------------------------------------------  MODULE NucleusSecurity_ContainerEscapePrevention  -------------------------------------------------
EXTENDS Naturals, Sequences, TLC

\* State constants
CONSTANTS
    contained

States == {
    contained
}

VARIABLES
    state,      \* Current state
    pc,         \* Program counter for step tracking
    history,    \* Sequence of visited states (for trace analysis)
    pending     \* Pending events/messages queue

vars == <<state, pc, history, pending>>

Init ==
    /\ state = contained
    /\ pc = 0
    /\ history = <<>>
    /\ pending = <<>>

\* Transition actions
Next ==
    UNCHANGED vars

\* Stuttering step (system does nothing)
Stutter ==
    UNCHANGED vars

Spec ==
    /\ Init
    /\ [][Next]_vars

\* Type invariant
TypeOK ==
    /\ state \in States
    /\ pc \in Nat
    /\ history \in Seq(States)

\* History length matches step count
HistoryConsistent ==
    Len(history) = pc

\* Temporal properties (LTL)
Prop_no_escape == []((state = contained) => ((state = contained)'))

\* Reachability helpers for model checking
CanReach_contained == <>(state = contained)

=============================================================
