\* AUTO-GENERATED by Intent compiler – do not edit by hand.
\* Re-generate with: intent compile <source>.intent
----------------------------------------------  MODULE Nucleus_Filesystem_FilesystemLifecycle  ----------------------------------------------
EXTENDS Naturals, Sequences, TLC

\* State values (defined as strings for Apalache)
unmounted == "unmounted"
mounted == "mounted"
populated == "populated"
pivoted == "pivoted"
unmounted_final == "unmounted_final"

States == {
    unmounted, mounted, populated, pivoted, unmounted_final
}

VARIABLES
    \* @type: Str;
    state,      \* Current state
    \* @type: Int;
    pc,         \* Program counter for step tracking
    \* @type: Seq(Str);
    history,    \* Sequence of visited states (for trace analysis)
    \* @type: Seq(Str);
    event_queue,     \* Pending events/messages queue
    \* @type: Str;
    action_taken,     \* MBT: name of the last action (for tla-connect replay)
    \* @type: Bool;
    context_populated,
    \* @type: Bool;
    tmpfs_mounted,
    \* @type: Int;
    persisted_file_count

vars == <<state, pc, history, event_queue, action_taken, context_populated, tmpfs_mounted, persisted_file_count>>

Init ==
    /\ state = unmounted
    /\ pc = 0
    /\ history = <<>>
    /\ event_queue = <<>>
    /\ action_taken = "init"
    /\ context_populated = FALSE
    /\ tmpfs_mounted = FALSE
    /\ persisted_file_count = 0

\* Transition actions
unmounted_mount_tmpfs ==
    /\ state = unmounted
    /\ state' = mounted
    /\ pc' = pc + 1
    /\ history' = Append(history, state)
    /\ event_queue' = event_queue
    /\ action_taken' = "unmounted_mount_tmpfs"
    /\ context_populated' = context_populated
    /\ tmpfs_mounted' = TRUE
    /\ persisted_file_count' = persisted_file_count

mounted_populate_context ==
    /\ state = mounted
    /\ state' = populated
    /\ pc' = pc + 1
    /\ history' = Append(history, state)
    /\ event_queue' = event_queue
    /\ action_taken' = "mounted_populate_context"
    /\ context_populated' = TRUE
    /\ tmpfs_mounted' = tmpfs_mounted
    /\ persisted_file_count' = 0

populated_pivot_root ==
    /\ state = populated
    /\ state' = pivoted
    /\ pc' = pc + 1
    /\ history' = Append(history, state)
    /\ event_queue' = event_queue
    /\ action_taken' = "populated_pivot_root"
    /\ context_populated' = context_populated
    /\ tmpfs_mounted' = tmpfs_mounted
    /\ persisted_file_count' = persisted_file_count

pivoted_cleanup ==
    /\ state = pivoted
    /\ state' = unmounted_final
    /\ pc' = pc + 1
    /\ history' = Append(history, state)
    /\ event_queue' = event_queue
    /\ action_taken' = "pivoted_cleanup"
    /\ context_populated' = FALSE
    /\ tmpfs_mounted' = FALSE
    /\ persisted_file_count' = 0

Next ==
    \/ unmounted_mount_tmpfs
    \/ mounted_populate_context
    \/ populated_pivot_root
    \/ pivoted_cleanup
    \/ UNCHANGED vars

\* Stuttering step (system does nothing)
Stutter ==
    UNCHANGED vars

Spec ==
    /\ Init
    /\ [][Next]_vars

\* Type invariant
TypeOK ==
    /\ state \in States
    /\ pc \in Nat
    /\ context_populated \in BOOLEAN
    /\ tmpfs_mounted \in BOOLEAN
    /\ persisted_file_count \in Nat
    \* history: checked via HistoryConsistent (Seq(States) unsupported by Apalache)

\* Terminal states
TerminalStates == {unmounted_final}

\* Once in terminal state, cannot leave
TerminalStable ==
    [](state \in TerminalStates => [](state \in TerminalStates))

\* History length matches step count
HistoryConsistent ==
    Len(history) = pc

\* Temporal properties (LTL)
Prop_context_isolation == [](state = pivoted => context_populated)
Prop_ephemeral_guarantee == [](state = unmounted_final => persisted_file_count = 0)
Prop_mount_ordering == [](state = populated => tmpfs_mounted)

\* State invariant for trace generation (negated to find terminating traces)
NotTerminated == state \notin TerminalStates

\* Liveness: Eventually reaches a terminal state
Liveness ==
    <>(state \in {unmounted_final})

\* Deadlock freedom: From every non-terminal state, some action is enabled
DeadlockFree ==
    [](state \notin TerminalStates => ENABLED(Next))

\* Reachability helpers for model checking
CanReach_unmounted == <>(state = unmounted)
CanReach_mounted == <>(state = mounted)
CanReach_populated == <>(state = populated)
CanReach_pivoted == <>(state = pivoted)
CanReach_unmounted_final == <>(state = unmounted_final)

==========================================================
