\* AUTO-GENERATED by Intent compiler — do not edit by hand.
\* Re-generate with: intent compile <source>.intent
------------------------------------------------  MODULE NucleusSecurity_Cgroups_ResourceLimiting  ------------------------------------------------
EXTENDS Naturals, Sequences, TLC

\* State constants
CONSTANTS
    unlimited, limited

States == {
    unlimited, limited
}

VARIABLES
    state,      \* Current state
    pc,         \* Program counter for step tracking
    history,    \* Sequence of visited states (for trace analysis)
    pending     \* Pending events/messages queue

vars == <<state, pc, history, pending>>

Init ==
    /\ state = unlimited
    /\ pc = 0
    /\ history = <<>>
    /\ pending = <<>>

\* Transition actions
unlimited_set_cgroup_limits ==
    /\ state = unlimited
    /\ state' = limited
    /\ pc' = pc + 1
    /\ history' = Append(history, state)
    /\ pending' = pending

Next ==
    \/ unlimited_set_cgroup_limits

\* Stuttering step (system does nothing)
Stutter ==
    UNCHANGED vars

Spec ==
    /\ Init
    /\ [][Next]_vars

\* Type invariant
TypeOK ==
    /\ state \in States
    /\ pc \in Nat
    /\ history \in Seq(States)

\* Terminal states
TerminalStates == {limited}

\* Once in terminal state, cannot leave
TerminalStable ==
    [](state \in TerminalStates => [](state \in TerminalStates))

\* History length matches step count
HistoryConsistent ==
    Len(history) = pc

\* Temporal properties (LTL)
Prop_limits_enforced == []((state = unlimited) => (<>(state = limited)))

\* Liveness: Eventually reaches a terminal state
Liveness ==
    <>(state \in {limited})

\* Deadlock freedom: From every non-terminal state, some action is enabled
DeadlockFree ==
    [](state \notin TerminalStates => ENABLED(Next))

\* Reachability helpers for model checking
CanReach_unlimited == <>(state = unlimited)
CanReach_limited == <>(state = limited)

============================================================
